name: Build and Email APK
on:
  push: 
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter 3.32.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

     

      - name: Build APK
        run: flutter build apk --release

      - name: Create apk_release folder
        run: |
          mkdir -p apk_release
          cp build/app/outputs/flutter-apk/app-release.apk apk_release/app-release.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: apk_release/app-release.apk
          
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "APK Release"
          tag_name: "v1.0.${{ github.run_number }}"
          files: apk_release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send APK link via SMS using TextBelt
        run: |
          curl -X POST https://textbelt.com/text \
            --data-urlencode phone='+201147857132' \
            --data-urlencode message="Your APK is ready! Download it here: https://github.com/${{ github.repository }}/releases/latest/download/app-release.apk" \
            --data-urlencode key=textbelt
